name: BYCONTRACT New
on:
  push:
  pull_request:
jobs:
  build:
    env: 
      CI: true
    runs-on: ubuntu-latest

    # Define the default workign directy for all runs
    defaults:
      run:
        working-directory: ./BYCONTRACTNEW
    
    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Git checkout ${{ github.ref_name}}
        uses: actions/checkout@v6
      
      - name: Install pnpm 
        uses: pnpm/action-setup@v6
        with:
          version: 10 #Version on my laptop
          cache: true
          run_install: |
            - recursive: true
              args: [--strict-peer-dependencies]
            - args: [--global,typescript]
      
      - name: Setup Nodejs ${{matrix.node-version}}
        uses: actions/setup-node@v6
        with:
          node-version: ${{ matrix.node-version}}
          cache: pnpm
          cache-dependency-path: "./BYCONTRACTNEW/pnpm-lock.yaml"


      - name:  install dependencies
        working-directory: BYCONTRACTNEW
        run: pnpm install
      
      - name: Run tests
        run: pnpm run test
